configuration: Release

image: Visual Studio 2017

before_build:
  - nuget restore ./NotesBackEnd/NotesBackEnd.sln

build:
  verbosity: minimal
  publish_wap: true

test:
   assemblies:
     except:
      - ./NotesBackEnd/tests/Notes.Api.Services.Tests/bin/Release/Notes.Comparers.dll
      - ./NotesBackEnd/tests/Notes.Api.Tests/bin/Release/Notes.Comparers.dll
      - ./NotesBackEnd/tests/Notes.Comparers/bin/Release/Notes.Comparers.dll
      - ./NotesBackEnd/tests/Notes.Services.Tests/bin/Release/Notes.Comparers.dll
      - ./NotesBackEnd/tests/Dependency.Tests/bin/Release/Notes.Comparers.dll
      - ./NotesBackEnd/tests/Services.Tests/bin/Release/Notes.Comparers.dll